# Render Blueprint Specification to automate deployment
services:
  - type: static_site
    name: ishingiroinitiatives
    buildCommand: npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
